environment:
  matrix:
  - CYG_ARCH: x86_64
    CYG_ROOT: C:/cygwin64
    CYG_CACHE: C:/cygwin64/var/cache/setup
    CYG_SH: C:/cygwin64/bin/bash -lc
    CYG_INSTALL: C:/cygwin64/setup-x86_64.exe -q -P
    CYG_PATH: C:/cygwin64/bin/cygpath -u

cache:
    - '%CYG_CACHE%'
    - C:/cygwin64/home/appveyor/fmm/build

init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - '%CYG_SH% "cygcheck -dc cygwin"'
    - '%CYG_INSTALL% "wget"'
    - '%CYG_SH% "wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg"'
    - '%CYG_SH% "install apt-cyg /bin"'
    - '%CYG_SH% "apt-cyg install make gcc-g++ cmake gdal libboost-devel zlib-devel libgdal-devel libexpat1-devel libbz2-devel"'
    - '%CYG_SH% "apt-cyg install swig python-devel"'

os: Visual Studio 2015

# clone directory
clone_folder: C:/cygwin64/home/appveyor/fmm

platform: x64

build_script:
  - '%CYG_SH% "cd fmm && mkdir build"'
  - '%CYG_SH% "cd fmm/build && cmake -G \"Unix Makefiles\" .. && make -j4 && make install"'
  - '%CYG_SH% "echo export \"PYTHONPATH=/home/appveyor/fmm/build/python:${PYTHONPATH}\" >> /home/appveyor/.bashrc"'

after_build:
  - '%CYG_SH% "echo $PYTHONPATH"'
  - '%CYG_SH% "echo $PATH"'
  - '%CYG_SH% "cd fmm/example/command_line_example;stmatch.exe stmatch_config.xml"'
  - '%CYG_SH% "cd fmm/example/python;python fmm_test.py"'

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - windows
