environment:
  matrix:
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    BUILD_SHARED_LIBS: ON

cache: c:\tools\vcpkg\installed\

init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

os: Visual Studio 2015

install:
    - cd c:\tools\vcpkg
    - git pull
    - .\bootstrap-vcpkg.bat
    - vcpkg install gdal
    - vcpkg install boost-geometry boost-graph boost-serialization bzip2 boost-program-options

# clone directory
clone_folder:  c:\projects\fmm

platform:      x64

build_script:
  - set PROJ_BUILD=%APPVEYOR_BUILD_FOLDER%\build
  - mkdir %PROJ_BUILD%
  - cd %PROJ_BUILD%
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake ..
  - make && make install

after_build:

on_finish:
  - ps:        $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - windows
