# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _fmm
else:
    import _fmm

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class MapMatcherConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, config_file):
        _fmm.MapMatcherConfig_swiginit(self, _fmm.new_MapMatcherConfig(config_file))
    network_file = property(_fmm.MapMatcherConfig_network_file_get, _fmm.MapMatcherConfig_network_file_set)
    network_id = property(_fmm.MapMatcherConfig_network_id_get, _fmm.MapMatcherConfig_network_id_set)
    network_source = property(_fmm.MapMatcherConfig_network_source_get, _fmm.MapMatcherConfig_network_source_set)
    network_target = property(_fmm.MapMatcherConfig_network_target_get, _fmm.MapMatcherConfig_network_target_set)
    ubodt_file = property(_fmm.MapMatcherConfig_ubodt_file_get, _fmm.MapMatcherConfig_ubodt_file_set)
    multiplier = property(_fmm.MapMatcherConfig_multiplier_get, _fmm.MapMatcherConfig_multiplier_set)
    nhash = property(_fmm.MapMatcherConfig_nhash_get, _fmm.MapMatcherConfig_nhash_set)
    delta = property(_fmm.MapMatcherConfig_delta_get, _fmm.MapMatcherConfig_delta_set)
    delta_defined = property(_fmm.MapMatcherConfig_delta_defined_get, _fmm.MapMatcherConfig_delta_defined_set)
    binary_flag = property(_fmm.MapMatcherConfig_binary_flag_get, _fmm.MapMatcherConfig_binary_flag_set)
    gps_error = property(_fmm.MapMatcherConfig_gps_error_get, _fmm.MapMatcherConfig_gps_error_set)
    k = property(_fmm.MapMatcherConfig_k_get, _fmm.MapMatcherConfig_k_set)
    radius = property(_fmm.MapMatcherConfig_radius_get, _fmm.MapMatcherConfig_radius_set)
    __swig_destroy__ = _fmm.delete_MapMatcherConfig

# Register MapMatcherConfig in _fmm:
_fmm.MapMatcherConfig_swigregister(MapMatcherConfig)

class MapMatcher(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, config_file):
        _fmm.MapMatcher_swiginit(self, _fmm.new_MapMatcher(config_file))
    __swig_destroy__ = _fmm.delete_MapMatcher

# Register MapMatcher in _fmm:
_fmm.MapMatcher_swigregister(MapMatcher)



